/* This file was generated by SableCC (http://www.sablecc.org/). 
 * Then modified.
 */

package ast.node;

/**
 * The IStatement subclass groups all nodes that are statements.
 * 
 * @author mstrout
 *
 */
public abstract class IStatement extends Node
{
    public String asmStartLabel;
    public String asmEndLabel;
    public int blockNumber;
    public IStatement(int _line_, int _pos_) {
        super(_line_,_pos_);
    }
}
